
# Data Catalogs
# Ubigeo Perú (Departamentos y principales provincias/ciudades)
UBIGEO_PERU = {
    "Amazonas": ["Chachapoyas", "Bagua", "Bongará", "Condorcanqui", "Luya", "Rodríguez de Mendoza", "Utcubamba"],
    "Áncash": ["Huaraz", "Aija", "Antonio Raymondi", "Asunción", "Bolognesi", "Carhuaz", "Carlos Fermín Fitzcarrald", "Casma", "Corongo", "Huari", "Huarmey", "Huaylas", "Mariscal Luzuriaga", "Ocros", "Pallasca", "Pomabamba", "Recuay", "Santa (Chimbote)", "Sihuas", "Yungay"],
    "Apurímac": ["Abancay", "Andahuaylas", "Antabamba", "Aymaraes", "Cotabambas", "Chincheros", "Grau"],
    "Arequipa": ["Arequipa", "Camaná", "Caravelí", "Castilla", "Caylloma", "Condesuyos", "Islay", "La Unión"],
    "Ayacucho": ["Ayacucho", "Cangallo", "Huanca Sancos", "Huanta", "La Mar", "Lucanas", "Parinacochas", "Páucar del Sara Sara", "Sucre", "Víctor Fajardo", "Vilcas Huamán"],
    "Cajamarca": ["Cajamarca", "Cajabamba", "Celendín", "Chota", "Contumazá", "Cutervo", "Hualgayoc", "Jaén", "San Ignacio", "San Marcos", "San Miguel", "San Pablo", "Santa Cruz"],
    "Callao": ["Callao"],
    "Cusco": ["Cusco", "Acomayo", "Anta", "Calca", "Canas", "Canchis", "Chumbivilcas", "Espinar", "La Convención", "Paruro", "Paucartambo", "Quispicanchi", "Urubamba"],
    "Huancavelica": ["Huancavelica", "Acobamba", "Angaraes", "Castrovirreyna", "Churcampa", "Huaytará", "Tayacaja"],
    "Huánuco": ["Huánuco", "Ambo", "Dos de Mayo", "Huacaybamba", "Huamalíes", "Leoncio Prado", "Marañón", "Pachitea", "Puerto Inca", "Lauricocha", "Yarowilca"],
    "Ica": ["Ica", "Chincha", "Nazca", "Palpa", "Pisco"],
    "Junín": ["Huancayo", "Chanchamayo", "Chupaca", "Concepción", "Jauja", "Junín", "Satipo", "Tarma", "Yauli"],
    "La Libertad": ["Trujillo", "Ascope", "Bolívar", "Chepén", "Gran Chimú", "Julcán", "Otuzco", "Pacasmayo", "Pataz", "Sánchez Carrión", "Santiago de Chuco", "Virú"],
    "Lambayeque": ["Chiclayo", "Ferreñafe", "Lambayeque"],
    "Lima": ["Lima", "Barranca", "Cajatambo", "Canta", "Cañete", "Huaral", "Huarochirí", "Huaura", "Oyón", "Yauyos"],
    "Loreto": ["Iquitos (Maynas)", "Alto Amazonas", "Loreto", "Mariscal Ramón Castilla", "Putumayo", "Requena", "Ucayali", "Datem del Marañón"],
    "Madre de Dios": ["Tambopata", "Manu", "Tahuamanu"],
    "Moquegua": ["Mariscal Nieto", "General Sánchez Cerro", "Ilo"],
    "Pasco": ["Pasco", "Daniel Alcides Carrión", "Oxapampa"],
    "Piura": ["Piura", "Ayabaca", "Huancabamba", "Morropón", "Paita", "Sullana", "Talara", "Sechura"],
    "Puno": ["Puno", "Azángaro", "Carabaya", "Chucuito", "El Collao", "Huancané", "Lampa", "Melgar", "Moho", "San Antonio de Putina", "San Román (Juliaca)", "Sandia", "Yunguyo"],
    "San Martín": ["Moyobamba", "Bellavista", "El Dorado", "Huallaga", "Lamas", "Mariscal Cáceres", "Picota", "Rioja", "San Martín (Tarapoto)", "Tocache"],
    "Tacna": ["Tacna", "Candarave", "Jorge Basadre", "Tarata"],
    "Tumbes": ["Tumbes", "Contralmirante Villar", "Zarumilla"],
    "Ucayali": ["Coronel Portillo (Pucallpa)", "Atalaya", "Padre Abad", "Purús"]
}

# Tipos de Vehículos y Marcas/Modelos comunes
VEHICULOS_DATA = {
    "Automóvil": {
        "Toyota":       ["Yaris", "Yaris Cross", "Corolla", "Corolla Cross", "Camry", "Etios",
                         "Avanza", "Prius", "Prius C", "Prius V", "Hilux", "Hilux SW4",
                         "Rav4", "Rav4 Hybrid", "Fortuner", "Land Cruiser", "Land Cruiser Prado",
                         "Rush", "FJ Cruiser", "Innova", "Innova Crysta", "4Runner", "Sequoia",
                         "Tundra", "Tacoma", "Sienna", "Venza", "C-HR", "bZ4X"],
        "Nissan":       ["Sentra", "Versa", "Tiida", "V-Drive", "Frontier", "Navara", "NP300",
                         "Kicks", "X-Trail", "Pathfinder", "Qashqai", "Murano", "Patrol",
                         "Terra", "Urvan", "NV350", "GT-R", "370Z", "Leaf", "Ariya"],
        "Hyundai":      ["Accent", "Elantra", "Elantra N", "i10", "Grand i10", "Tucson",
                         "Santa Fe", "Creta", "Venue", "H-1", "Starex", "Sonata", "Ioniq",
                         "Ioniq 5", "Ioniq 6", "Casper", "Palisade", "Nexo", "Staria"],
        "Kia":          ["Rio", "Cerato", "Picanto", "Soluto", "Sportage", "Sorento",
                         "Seltos", "Sonet", "Carnival", "Stinger", "Telluride", "EV6",
                         "Niro", "Mohave", "K3", "K5", "K8"],
        "Honda":        ["City", "Civic", "Civic Type R", "Accord", "CR-V", "HR-V", "WR-V",
                         "Jazz", "Fit", "Pilot", "Odyssey", "Ridgeline", "Brio", "BR-V",
                         "ZR-V", "e:N1", "Mobilio"],
        "Subaru":       ["Impreza", "Impreza Sport", "Legacy", "Outback", "Forester",
                         "XV", "Crosstrek", "WRX", "WRX STI", "BRZ", "Ascent", "Exiga",
                         "Tribeca", "Baja", "Solterra"],
        "Chevrolet":    ["Spark", "Onix", "Onix Plus", "Sail", "Prisma", "Tracker",
                         "Captiva", "Blazer", "Equinox", "Traverse", "Trailblazer",
                         "Colorado", "Colorado Z71", "D-Max", "Silverado", "Suburban",
                         "Tahoe", "Cruze", "Malibu", "Camaro", "Corvette", "Trax",
                         "Montana", "Groove"],
        "Suzuki":       ["Alto", "Celerio", "Swift", "Dzire", "Baleno", "Ciaz",
                         "Ignis", "Vitara", "Grand Vitara", "Grand Vitara XL7",
                         "S-Cross", "Jimny", "Jimny Sierra", "Ertiga", "XL6", "Fronx",
                         "Brezza", "Carry"],
        "Volkswagen":   ["Gol", "Polo", "Virtus", "Vento", "Jetta", "Golf", "Golf GTI",
                         "Golf R", "Passat", "Arteon", "T-Cross", "T-Roc", "Tiguan",
                         "Tiguan Allspace", "Touareg", "Touran", "Amarok", "Transporter",
                         "Caravelle", "Multivan", "ID.4", "ID.6", "Saveiro"],
        "Mazda":        ["Mazda 2", "Mazda 3", "Mazda 3 Sedan", "Mazda 6", "CX-3",
                         "CX-30", "CX-5", "CX-50", "CX-60", "CX-70", "CX-80", "CX-90",
                         "BT-50", "MX-5", "MX-30", "RX-8"],
        "Ford":         ["Ka", "Fiesta", "Focus", "Mondeo", "Fusion", "Mustang", "Mustang Mach-E",
                         "EcoSport", "Escape", "Edge", "Explorer", "Expedition", "Bronco", "Bronco Sport",
                         "Territory", "Ranger", "Ranger Raptor", "F-150", "F-150 Lightning",
                         "F-250", "F-350", "Transit", "Transit Connect", "E-Transit"],
        "Mitsubishi":   ["Mirage", "Mirage G4", "Outlander", "Outlander Sport", "ASX",
                         "Eclipse Cross", "Galant", "Xpander", "L200", "Montero Sport",
                         "Pajero", "Pajero Sport", "L300", "Colt", "Lancer"],
        "Renault":      ["Kwid", "Logan", "Sandero", "Symbol", "Fluence", "Mégane",
                         "Zoe", "Duster", "Captur", "Koleos", "Oroch", "Alaskan",
                         "Master", "Trafic", "Kangoo", "Express"],
        "Peugeot":      ["107", "108", "208", "308", "408", "508", "2008", "3008", "5008",
                         "301", "401", "Partner", "Expert", "Boxer", "Landtrek",
                         "Rifter", "Traveller"],
        "Fiat":         ["Mobi", "Uno", "Palio", "Siena", "Argo", "Cronos",
                         "Tipo", "Pulse", "Fastback", "Toro", "Strada", "Ducato",
                         "Doblo", "Fiorino", "Scudo", "500", "500X", "Panda"],
        "Mercedes-Benz":["Clase A", "Clase B", "Clase C", "Clase E", "Clase S", "Clase G",
                         "CLA", "CLS", "SL", "SLC", "AMG GT",
                         "GLA", "GLB", "GLC", "GLE", "GLS", "EQA", "EQB", "EQC",
                         "EQE", "EQS", "Sprinter", "Vito", "Viano", "Actros"],
        "BMW":          ["Serie 1", "Serie 2", "Serie 2 Gran Coupe", "Serie 3", "Serie 4",
                         "Serie 5", "Serie 6", "Serie 7", "Serie 8",
                         "X1", "X2", "X3", "X4", "X5", "X6", "X7", "iX",
                         "M2", "M3", "M4", "M5", "M6", "M8",
                         "i3", "i4", "i5", "i7"],
        "Audi":         ["A1", "A3", "A4", "A5", "A6", "A7", "A8",
                         "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8",
                         "TT", "TTS", "R8",
                         "S3", "S4", "S5", "S6", "S7", "S8",
                         "RS3", "RS4", "RS5", "RS6", "RS7", "e-tron"],
        "Jeep":         ["Renegade", "Compass", "Cherokee", "Grand Cherokee",
                         "Grand Cherokee L", "Wrangler", "Gladiator", "Commander",
                         "Grand Wagoneer", "Meridian"],
        "Dodge":        ["Challenger", "Charger", "Durango", "Journey",
                         "RAM 1500", "RAM 2500", "RAM 3500", "RAM ProMaster"],
        "RAM":          ["1500", "1500 TRX", "2500", "3500", "4500", "ProMaster", "ProMaster City"],
        "Land Rover":   ["Defender 90", "Defender 110", "Defender 130",
                         "Discovery", "Discovery Sport",
                         "Range Rover", "Range Rover Sport", "Range Rover Velar",
                         "Range Rover Evoque", "Freelander"],
        "Volvo":        ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90",
                         "C40", "EX30", "EX90"],
        "Porsche":      ["911", "Boxster", "Cayman", "Cayenne", "Macan",
                         "Panamera", "Taycan", "718"],
        "Lexus":        ["IS", "ES", "GS", "LS", "CT", "UX", "NX",
                         "RX", "GX", "LX", "LC", "RC"],
        "Infiniti":     ["Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX55", "QX60", "QX80"],
        "Acura":        ["ILX", "TLX", "RLX", "MDX", "RDX", "NSX", "Integra"],
        "Lincoln":      ["Navigator", "Navigator L", "Aviator", "Corsair", "Nautilus", "Continental"],
        "Cadillac":     ["CT4", "CT5", "Escalade", "Escalade ESV", "XT4", "XT5", "XT6", "LYRIQ"],
        "Chery":        ["Tiggo 2", "Tiggo 2 Pro", "Tiggo 4", "Tiggo 4 Pro", "Tiggo 5x",
                         "Tiggo 7", "Tiggo 7 Pro", "Tiggo 8", "Tiggo 8 Pro",
                         "Arrizo 3", "Arrizo 5", "Arrizo 5 Pro", "Arrizo 6", "Arrizo 8"],
        "Changan":      ["CS15", "CS35", "CS35 Plus", "CS55", "CS55 Plus", "CS75",
                         "CS75 Plus", "CS85", "CS95", "CX70", "Alsvin",
                         "UNI-T", "UNI-K", "UNI-V", "Hunter", "Oshan X7"],
        "JAC":          ["S2", "S3", "JS4", "JS6", "T6", "T8", "T9",
                         "Sei 2", "Sei 4", "Sei 4 Pro", "Sei 6", "A60",
                         "e-S4", "iEV7S"],
        "MG":           ["MG 3", "MG 5", "MG 6", "MG 7", "HS",
                         "HS PHEV", "ZS", "ZS EV", "RX5", "GS",
                         "Extender", "One", "VS"],
        "Geely":        ["Coolray", "Okavango", "Emgrand", "Azkarra",
                         "GX2", "GX3", "GX6", "Atlas", "Atlas Pro",
                         "MK", "MK Cross", "Boyue", "Preface", "Xingyue"],
        "BYD":          ["Atto 3", "Seagull", "Dolphin", "Han", "Tang",
                         "Song", "Song Plus", "Song Pro", "Qin", "Qin Plus",
                         "Yuan Plus", "King", "Destroyer 05", "Seal", "Sea Lion 6",
                         "e2", "e3", "e5", "e6"],
        "Haval":        ["H2", "H4", "H6", "H6 GT", "H9", "H11",
                         "Jolion", "Dargo", "Big Dog", "Concept H", "F7", "F7x"],
        "GWM / Great Wall": ["Wingle", "Wingle 5", "Wingle 6", "Wingle 7",
                              "Cannon", "Poer", "Ora", "Pao"],
        "DFSK / Sokon": ["Fengon 500", "Fengon 580", "Fengon 600", "Fengon 700",
                          "K01", "K07", "K07S", "C37", "Glory 500", "Glory 560", "Glory 580"],
        "Isuzu":        ["D-Max", "D-Max LS", "D-Max Hi-Lander", "MU-X", "Trooper",
                         "Fuego", "TF", "NKR", "NPR", "NQR", "FSR", "FTR", "FVR", "GVR"],
        "SsangYong":    ["Rexton", "Rexton Sports", "Tivoli", "Tivoli XLV",
                         "Korando", "Musso", "Torres", "Rodius"],
        "Foton":        ["Tunland", "Tunland G9", "Gratour", "Toano",
                         "View CS2", "Aumark", "Auman", "BJ40"],
        "GAC":          ["GS4", "GS5", "GS8", "Emkoo", "Emzoom",
                         "Aion S", "Aion S Plus", "Aion Y", "Trumpchi M6"],
        "Citroën":      ["C3", "C3 Aircross", "C4", "C4 Cactus", "C5 Aircross",
                         "Berlingo", "Spacetourer", "Jumper", "Jumpy", "C-Elysée"],
        "Opel / Vauxhall": ["Corsa", "Astra", "Insignia", "Mokka", "Crossland",
                             "Grandland", "Zafira", "Combo", "Vivaro", "Movano"],
        "Alfa Romeo":   ["Giulia", "Giulietta", "Stelvio", "Tonale",
                         "MiTo", "147", "156", "159", "Brera"],
        "Seat":         ["Ibiza", "Arona", "Leon", "Ateca", "Tarraco",
                         "Toledo", "Alhambra", "Altea", "Mii"],
        "Skoda":        ["Fabia", "Octavia", "Superb", "Kamiq", "Karoq",
                         "Kodiaq", "Scala", "Enyaq", "Rapid"],
        "Tesla":        ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
        "Lincoln / Mercury": ["Town Car", "MKZ", "MKS", "MKT", "MKX", "MKC"],
    },
    "Moto Lineal": {
        "Honda":        ["CB125F", "CB190R", "CB300R", "CB500F", "CB650R", "CB1000R",
                         "CBR300R", "CBR500R", "CBR600RR", "CBR1000RR",
                         "XR150L", "XR190L", "XRE300", "XRE190",
                         "CRF250L", "CRF300L", "CRF450R",
                         "Wave 110", "Wave 125", "Dio", "Navi", "Elite", "GL150",
                         "Africa Twin", "Transalp 750", "NC750X"],
        "Yamaha":       ["YZF-R3", "YZF-R6", "YZF-R7", "YZF-R15", "YZF-R1",
                         "MT-03", "MT-07", "MT-09", "MT-10",
                         "FZ-S", "FZ 25", "FZ-S FI",
                         "XTZ 125", "XTZ 150", "XTZ 250", "Ténéré 700",
                         "NMAX 155", "AEROX 155", "Cygnus Ray", "BW'S 125",
                         "TMAX 560", "XMAX 300", "Tracer 7", "Tracer 9"],
        "Bajaj":        ["Pulsar NS125", "Pulsar NS160", "Pulsar NS200",
                         "Pulsar N150", "Pulsar N250", "Pulsar RS200",
                         "Pulsar 150", "Pulsar 160 F",
                         "Dominar 250", "Dominar 400",
                         "Avenger 160", "Avenger 220",
                         "CT100", "CT110", "Platina 110",
                         "Boxer 150", "Discover 100", "Discover 125"],
        "Suzuki":       ["GSX-R150", "GSX-R1000", "GSX-S150", "GSX-S750",
                         "Gixxer 150", "Gixxer 250", "Burgman 200",
                         "V-Strom 650", "V-Strom 1000",
                         "GN125", "GN125F", "Hayabusa",
                         "Inazuma 250", "SV650"],
        "Kawasaki":     ["Ninja 300", "Ninja 400", "Ninja 650", "Ninja ZX-6R", "Ninja ZX-10R",
                         "Z300", "Z400", "Z650", "Z900", "Z1000",
                         "Versys 300", "Versys 650", "Versys 1000",
                         "Vulcan S", "KLX150", "KLX230", "KLX300",
                         "KX250", "KX450"],
        "KTM":          ["125 Duke", "200 Duke", "250 Duke", "390 Duke",
                         "790 Duke", "890 Duke", "1290 Super Duke",
                         "RC 125", "RC 200", "RC 390",
                         "390 Adventure", "790 Adventure", "890 Adventure",
                         "250 EXC", "300 EXC", "450 EXC", "500 EXC",
                         "85 SX", "150 SX", "250 SX"],
        "Triumph":      ["Street Triple R", "Street Triple RS", "Speed Triple",
                         "Tiger 660", "Tiger 800", "Tiger 900", "Tiger 1200",
                         "Bonneville T100", "Bonneville T120", "Scrambler 400",
                         "Trident 660", "Daytona Moto2"],
        "Wanxin":       ["WX150", "WX200", "WX250", "Cross 200", "Cross 250", "WX300"],
        "Ronco":        ["Pantera 150", "X-Treme 200", "Demolition 250", "Aguila 150", "Force 200"],
        "Italika":      ["FT150", "FT200", "DM200", "DT150", "DT200", "WS150", "WS175"],
        "Zongshen":     ["ZS150", "ZS200", "RX1", "RX3", "TX3", "ZS250"],
        "Ssenda":       ["K-Sport 150", "Eco 150", "Dakar 200", "Dakar 250", "Trail 200"],
        "Lifan":        ["LF150", "KPR 200", "KP 200", "KPR 150", "LF250"],
        "CF Moto":      ["150NK", "250NK", "300NK", "400NK", "650NK", "650MT", "800MT"],
        "Royal Enfield":["Classic 350", "Classic 500", "Bullet 350",
                         "Meteor 350", "Hunter 350", "Himalayan 450",
                         "Interceptor 650", "Continental GT 650",
                         "Thunderbird 350X", "Scram 411"],
        "Harley-Davidson": ["Sportster 883", "Sportster 1200", "Iron 883",
                             "Street 500", "Street 750",
                             "Road King", "Street Glide", "Fat Boy",
                             "Softail Standard", "Sportster S"],
    },
    "Mototaxi": {
        "Bajaj":        ["Torito GX 4T", "Torito 2T", "Maxima Cargo", "Maxima Z", "RE 4S"],
        "TVS":          ["King Duramax", "King Deluxe", "King Kargo", "King Duramax ES"],
        "Piaggio":      ["Ape City", "Ape Xtra LDX", "Ape TRE"],
        "Wanxin":       ["Torito WX 150", "Mototaxi WX 200", "Force Cargo 200"],
        "Ronco":        ["Mototaxi R 150", "Ronco Cargo 200"],
        "Ssenda":       ["Mototaxi S 150", "Cargo S 200"],
        "Zongshen":     ["ZS200GY", "ZS250GY"],
        "Italika":      ["TF150", "TF200"],
        "Hero":         ["Navi", "Optima CX"],
    },
    "Moto Furgón": {
        "Wanxin":       ["Furgón 250", "Furgón 300", "Carguero 200", "Carguero 300"],
        "Ronco":        ["Aguila Cargo 300", "Hercules 300", "Cargo 250"],
        "Zongshen":     ["Cargo 250", "Cargo 300", "ZS250GY-C"],
        "Ssenda":       ["Cargo 200", "Cargo 250", "Cargo 300"],
        "Lifan":        ["LF200ZH", "LF250ZH", "LF300ZH"],
        "Daytona":      ["Furgón DT250", "Cargo 200"],
        "Loncin":       ["Cargo 200", "Cargo 250"],
        "Kiden":        ["Furgón KD250", "Furgón KD300"],
    },
    "Camión": {
        "Volkswagen":   ["Constellation", "Worker", "Delivery", "e-Delivery"],
        "Mercedes-Benz":["Actros", "Axor", "Atego", "Accelo", "Arocs", "Sprinter Cargo"],
        "Volvo":        ["FH", "FM", "FMX", "FE", "FL"],
        "Scania":       ["R Series", "S Series", "G Series", "P Series", "L Series"],
        "Man":          ["TGX", "TGS", "TGM", "TGL"],
        "Hyundai":      ["HD35", "HD65", "HD72", "HD75", "HD78", "HD120", "HD170"],
        "Isuzu":        ["ELF", "FRR", "FSR", "FTR", "FVR", "GVR", "GIGA"],
        "Mitsubishi Fuso": ["Canter", "Fighter", "Shogun", "Super Great"],
        "Foton":        ["Aumark", "Auman", "Galaxy"],
        "JAC":          ["N35", "N56", "N75", "N120", "N350"],
        "Hino":         ["300", "500", "700", "XZU", "FC", "GH"],
        "FAW":          ["J5", "J6", "Besturn", "Tiger V", "Heavy"],
        "Dongfeng":     ["DFM", "Captain", "KX", "KX7", "KC"],
    },
    "Minivan / Furgoneta": {
        "Toyota":       ["Hiace", "Sienna", "Alphard", "Vellfire", "HiAce Wagon"],
        "Nissan":       ["Urvan", "NV350", "NV200", "Caravan"],
        "Hyundai":      ["H-1", "Staria", "Starex"],
        "Kia":          ["Carnival", "Bongo"],
        "Mercedes-Benz":["Vito", "Viano", "Sprinter"],
        "Volkswagen":   ["Transporter", "Multivan", "Caravelle", "Crafter"],
        "Ford":         ["Transit", "Transit Connect", "Tourneo"],
        "Renault":      ["Master", "Trafic", "Kangoo"],
        "Peugeot":      ["Expert", "Traveller", "Boxer"],
        "Fiat":         ["Ducato", "Talento", "Doblo"],
    }
}


def get_marcas(tipo):
    return sorted(list(VEHICULOS_DATA.get(tipo, {}).keys()))

def get_modelos(tipo, marca):
    return sorted(VEHICULOS_DATA.get(tipo, {}).get(marca, []))

def get_all_marcas_autos():
    """Retorna todas las marcas de Automóvil ordenadas alfabéticamente"""
    return sorted(list(VEHICULOS_DATA.get("Automóvil", {}).keys()))

def get_all_modelos(marca):
    """Retorna modelos de cualquier tipo que tenga esa marca"""
    modelos = set()
    for tipo_data in VEHICULOS_DATA.values():
        if marca in tipo_data:
            modelos.update(tipo_data[marca])
    return sorted(list(modelos))
